version: "3"

includes:
  lint: ./scripts/lint.yml
  fmt: ./scripts/fmt.yml

tasks:
  cfg:scripts:
    run: once
    desc: Configure Scripts to be executable
    cmds:
      - chmod -R +x ./scripts
  build:
    desc: Builds Docker image
    cmds:
      - docker build -t=kirinnee/nix-docker:{{.CLI_ARGS}} .
  run:
    desc: Builds and runs the docker image
    cmds:
      - ./scripts/run.sh {{.CLI_ARGS}}
  # Utility
  lint:
    desc: Run all linters
    cmds:
      - task: lint:php
      - task: lint:sh
      - task: lint:docker
  fmt:
    desc: Run all formatters
    cmds:
      - task: fmt:php
      - task: fmt:sh
      - task: fmt:md
      - task: fmt:yaml
      - task: fmt:nix
